# Generated by Django 6.0.2 on 2026-04-17 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_ratings_alter_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
